server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_billing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: YOUR_DB_USER
    password: YOUR_DB_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:seed.sql
      continue-on-error: true

logging:
  level:
    org.hibernate.SQL: debug

crm:
  mockoon:
    base-url: http://localhost:8080
    customers-path: /crm/customers
    contracts-path: /crm/contracts
  auto-create-offers: true
  default-service-unit: OCTET
  default-unit-price: 0

billing:
  scheduler:
    enabled: true
    cron: "0 30 2 1 * *"
    zone: "UTC"
